#!/bin/sh -e

echo "0.15.0" > RELEASE-VERSION
export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/ \
    -DENABLE_STATIC=OFF \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib

cmake --build   build
cmake --install build
