#!/bin/sh -e

make

mkdir _completions
bin/gh completion -s bash > ./_completions/bash
bin/gh completion -s zsh > ./_completions/zsh
bin/gh completion -s fish > ./_completions/fish

install -Dm644 "_completions/bash" "$1/usr/share/bash-completion/completions/gh"
install -Dm644 "_completions/zsh" "$1/usr/share/zsh/site-functions/_gh"

install -Dm755 "bin/gh" "$1/usr/bin/gh"
install -Dm644 "LICENSE" "$1/usr/share/licenses/github-cli"

