#!/bin/sh -e

sed -e 's%#include <ipset%#include <libcorkipset%' \
		-e 's%#include "ipset%#include "libcorkipset%' \
		-i include/ipset/*.h */*/*/*.c */*/*/*.c.in */*/*.c */*.c
mv include/ipset include/libcorkipset

cmake . \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DCMAKE_BUILD_STYLE=Release

make

make DESTDIR="$1" install
