#!/bin/sh -e

./autogen.sh
./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--localstatedir=/var \
		--enable-shared \
		--enable-system-shared-lib 
            

make

make DESTDIR="$1" PREFIX=/usr install
