#!/bin/sh -e

./autogen.sh
./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--enable-shared \
		--enable-system-shared-lib \
        --disable-documentation \
            

make
make DESTDIR="$1" PREFIX=/usr install
