#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

#git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
#sed -i 's|AC_CONFIG_FILES(\[libbloom/Makefile libcork/Makefile libipset/Makefile\])||' configure.ac

./autogen.sh

./configure \
    --prefix=/usr \
    --enable-shared \
    --enable-system-shared-lib \
    --disable-documentation 

make
make DESTDIR="$1" install
