#!/bin/sh -e

NOCONFIGURE=1 ./autogen.sh
default_prepare

./configure \
		--build=$CBUILD \
		--host=$CHOST \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--with-priv-mode=setuid

make
make DESTDIR="$1" install
