#!/bin/sh -e

makeopts="NO_ICONV=YesPlease
    NO_GETTEXT=YesPlease
    NO_TCLTK=YesPlease
    NO_SVN_TESTS=YesPlease
    NO_REGEX=NeedsStartEnd
    NO_LUA=1
    prefix=/usr"


make get-git
make $makeopts 
make CGIT_SCRIPT_PATH=/usr/share/webapps/cgit DESTDIR="$1" prefix=/usr install

ln -s cgit.cgi "$1/usr/share/webapps/cgit/cgit"
