#!/bin/sh -e

./configure \
        --prefix=/usr \
		--with-editor=/usr/bin/vi \
		--with-spooldir=/var/spool/fcron \
		--sysconfdir=/etc/fcron \
		--with-answer-all=no \
		--with-boot-install=no \
		--localstatedir=/var \
		--with-piddir=/run \
		--with-sendmail=no \
		--with-selinux=no \
		--with-systemdsystemunitdir=no

make
make DESTDIR="$1" install

install -Dm775 fcron.initd "$1/etc/init.d/fcron"
install -Dm640 systab.orig "$1/var/spool/fcron/systab.orig"
install -Dm644 fcron.pam "$1/etc/pam.d/fcron"
install -Dm644 fcrontab.pam "$1/etc/pam.d/fcrontab"

