#!/bin/sh -e

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-shared \
    --disable-static 
            

make
make DESTDIR="$1" install

install -Dm644 liba52/a52_internal.h "$1/usr/include/a52dec"
