#!/bin/sh -e

cd src

make proot proot.static

install -Dm755 proot "$1/usr/bin/proot"
install -Dm755 proot.static "$1/usr/bin/proot.static"
install -Dm644 "$2/doc/proot/man.1" "$1/usr/share/man/man1/proot.1"

