#!/bin/sh -e

export _cli_builddir=components/cli
export _daemon_builddir=components/engine
export _buildtags="seccomp"
export _libnetwork_builddir=libnetwork-$_libnetwork_ver

export AUTO_GOPATH=1
export GITCOMMIT=$_gitcommit		# for cli
export DOCKER_GITCOMMIT=$_gitcommit	# for engine
export DOCKER_BUILDTAGS=$_buildtags
unset CC


echo "building docker-proxy"
cd "$_libnetwork_builddir"
mkdir -p src/github.com/docker/
ln -s "$_libnetwork_builddir" src/github.com/docker/libnetwork
GOPATH="$PWD" go build -v -ldflags="-linkmode=external" -o docker-proxy github.com/docker/libnetwork/cmd/proxy

# daemon
echo "building daemon"
cd "$_daemon_builddir"
mkdir -p src/github.com/docker/
ln -s "$_daemon_builddir" src/github.com/docker/docker
GOPATH="$PWD" VERSION="19.03.12" hack/make.sh dynbinary

# Required for building man-pages
export GOPATH="$_cli_builddir"
export GOBIN="$GOPATH/bin"
export PATH="$GOBIN:$PATH"

# cli
echo "building cli"
cd "$_cli_builddir"
mkdir -p "$GOPATH"/src/github.com/docker/
ln -s "$_cli_builddir" "$GOPATH"/src/github.com/docker/cli
LDFLAGS="" make VERSION="19.03.12" BUILDMODE=$_buildmode dynbinary

# docker man
echo "building docker man pages"
# cobra
mkdir -p "$GOPATH"/src/github.com/spf13/
ln -sf "$PWD"/cobra-$_cobra_ver "$GOPATH"/src/github.com/spf13/cobra

# convert md to man pages
echo "generating man pages"
cd "$_cli_builddir"

# make manpages (from cli/Makefile, but using installed go-md2ma
mkdir -p ./man/man1

# Generate man pages from cobra commands
go build -o /tmp/gen-manpages github.com/docker/cli/man
/tmp/gen-manpages --root "$(pwd)" --target "$(pwd)/man/man1"

# generate legacy manpages from markdown
./man/md2man-all.sh -q
install -Dm755 "$_daemon_builddir"/bundles/dynbinary-daemon/dockerd "$1/usr/bin/dockerd"
install -Dm755 "$_libnetwork_builddir"/docker-proxy "$1/usr/bin/docker-proxy"

# symlink externally provided tini-static binary
ln -s "$1/sbin/tini-static" "$subpkgdir"/usr/bin/docker-init

# YAY
install -Dm755 docker.initd "$1/etc/init.d/docker"
install -Dm644 docker.confd "$1/etc/conf.d/docker"

# 'build/docker' is a symlink to 'docker-linux-$arch' e.g. 'docker-linux-amd64'
install -Dm755 "$_cli_builddir"/build/docker "$1/usr/bin/docker"
install -Dm644 "$_cli_builddir"/contrib/completion/bash/docker "$1/usr/share/bash-completion/completions/docker"
nstall -Dm644 "$_cli_builddir"/contrib/completion/zsh/_docker "$1/usr/share/zsh/site-functions/_docker"
