#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --bindir=/usr/bin \
    --localstatedir=/var/lib/xbps \
    --enable-lto

sed 's|-O2|-Os|g' config.mk

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/*.a"
