#!/bin/sh -e

export GOPATH=$PWD

cd containerd

make
make DESTDIR="$1" install

install -Dm755 run "$1/etc/sv/containerd/run"
install -Dm755 run "$1/etc/sysmgr/containerd"
ln -s /run/runit/supervise.containerd "$1/etc/sv/containerd/supervise"
