#!/bin/sh -e

/configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--sbindir=/usr/bin \
		--enable-anacron \
		--with-inotify \
        --without-selinux \
        --enable-pie \
        --enable-relro \
		--with-pam

make
make DESTDIR="$1" install

# crontab must be setuid
chmod u+s "$1/usr/bin/crontab"

install -d "$1/var/spool/{ana,}cron"
install -d "$1/etc/cron.{d,hourly,daily,weekly,monthly}"

 # Add /etc/cron.deny empty, to allow all users.
install -Dm0644 deny "$1/etc/cron.deny"
install -Dm0644 pam.d "$1/etc/pam.d/crond"

# Install anacron related files
install -Dm0644 contrib/anacrontab "$1/etc/anacrontab"
install -Dm0644 contrib/0hourly "$1/etc/cron.d/0hourly"
install -Dm0755 contrib/0anacron "$1/etc/cron.hourly/0anacron"
