#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

make
make DESTDIR="$1" install

#find . -name "*.crt" -exec mv "$1/etc/ssl/certs/ca-certificates.crt";

#cp -r "$1/usr/sbin/" "$1/usr/bin"

#rm -rf "$1/usr/sbin"
