#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

make
make DESTDIR="$1" install

for i in $(ls *.crt | sort); do
        cat "$i"
        printf "\n"
done > "$1/etc/ssl/certs/ca-certificates.crt"
