#!/bin/sh -e

sed -e '19d' configure.ac 

./configure \
    --prefix=/usr \
    --disable-drm \
    --enable-randr \
    --disable-geoclue \
    --disable-geoclue2 \
    --disable-ubuntu \
    --disable-vidmode \
    --disable-gui \
    --disable-nls

make
make DESTDIR="$1" install

install -Dm644 redshift.conf.sample "$1/usr/share/doc/redshift/examples/redshift.conf"
