#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

./build.sh

install -Dm755 lite "$1/usr/bin/lite"
install -d "$1/usr/share/lite"

cp -r data/* "$1/usr/share/lite/"

cp autoinsert.lua "$1/usr/share/lite/plugins"
cp autowrap.lua "$1/usr/share/lite/plugins"
cp bracketmatch.lua "$1/usr/share/lite/plugins"
cp colorpreview.lua "$1/usr/share/lite/plugins"
cp console.lua "$1/usr/share/lite/plugins"
cp detectindent.lua "$1/usr/share/lite/plugins"
cp indentguide.lua "$1/usr/share/lite/plugins"
cp language_hs.lua "$1/usr/share/lite/plugins"
cp language_nim.lua "$1/usr/share/lite/plugins"
cp language_rust.lua "$1/usr/share/lite/plugins"
cp language_sh.lua "$1/usr/share/lite/plugins"
cp linter_nim.lua "$1/usr/share/lite/plugins"
cp linter_shellcheck.lua "$1/usr/share/lite/plugins"
cp togglesnakecamel.lua "$1/usr/share/lite/plugins"
cp workspace.lua "$1/usr/share/lite/plugins"
cp linter.lua "$1/usr/share/lite/plugins"

cp duotone.lua "$1/usr/share/lite/user/colors"
