#!/bin/sh -e

cmake \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=True \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DINSTALL_LIBDIR=usr/lib \
    -DINSTALL_INCLUDEDIR=usr/include/mysql \
    -DMARIADB_PORT=3306 \
    -DMARIADB_UNIX_ADDR=/run/mysqld/mysqld.sock \
    -DWITH_EXTERNAL_ZLIB=YES \
    -DWITH_MYSQLCOMPAT=ON \
    -DWITH_SSL=LIBRESSL 

make
make DESTDIR="$1" install
