#!/bin/sh -e
#sed -i 's|AC_CONFIG_FILES(\[libbloom/Makefile libcork/Makefile libipset/Makefile\])||' configure.ac

echo "0.15.0" > RELEASE-VERSION

patch -p1 < fix-dumb-script.patch
rm src/CMakeLists.txt

cmake  \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib

make
make DESTDIR="$1" install
