#!/bin/sh -e

patch -p1 < always-install-executables.patch
patch -p1 < dont-set-rpath.patch

cmake . \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DCMAKE_SKIP_BUILD_RPATH=ON

make
make DESTDIR="$1" PREFIX=/usr install

mv "$1/usr/lib/libwoff2common.so.*" "$1/usr/lib"
mv "$1/usr/lib/libwoff2enc.so.*" "$1/usr/lib"
mv "$1/usr/lib/libwoff2dec.so.*"  "$1/usr/lib"

install -Dt "$1/usr/share/licenses/woff2" -m644 woff2/LICENSE
