#!/bin/sh -e

patch -p1 < always-install-executables.patch
patch -p1 < dont-set-rpath.patch

cmake . \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DCMAKE_SKIP_BUILD_RPATH=ON

make
make DESTDIR="$1" PREFIX=/usr install
