#!/bin/sh -e

sed -i 's/NOT BUILD_SHARED_LIBS/TRUE/' CMakeLists.txt

cmake . \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DCMAKE_SKIP_BUILD_RPATH=ON
make
make DESTDIR="$1" PREFIX=/usr install

install -Dt "$1/usr/share/licenses/woff2" -m644 woff2/LICENSE
